version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: foo
      MYSQL_DATABASE: kawandesa
      MYSQL_USER: foo
      MYSQL_PASSWORD: pw
    ports:
      - "3306:3306"
